language: python

cache: pip

python:
    - "3.4"
    - "3.5-dev"
    - "nightly"

sudo: required
dist: trusty


install:
    - python setup.py install
    - pip install -r requirements.txt
    - pip install -U pip codecov coveralls

script:
    - coverage run --source=kittengroomer_email setup.py test

notifications:
    email:
        on_success: change
        on_failure: change

after_success:
    - coveralls
    - codecov
