language: python

python:
    - "3.3"
    - "3.4"
    - "3.5"
    - "nightly"

dist: trusty


install:
    - python setup.py install
    - pip install -r requirements.txt
    - pip install codecov coveralls
    - pushd tests/mail_src
    - wget http://www.aueb.gr/users/ion/data/enron-spam/raw/ham/beck-s.tar.gz  http://www.aueb.gr/users/ion/data/enron-spam/raw/ham/farmer-d.tar.gz http://www.aueb.gr/users/ion/data/enron-spam/raw/ham/kaminski-v.tar.gz http://www.aueb.gr/users/ion/data/enron-spam/raw/ham/kitchen-l.tar.gz  http://www.aueb.gr/users/ion/data/enron-spam/raw/ham/lokay-m.tar.gz http://www.aueb.gr/users/ion/data/enron-spam/raw/ham/williams-w3.tar.gz http://www.aueb.gr/users/ion/data/enron-spam/raw/spam/BG.tar.gz  http://www.aueb.gr/users/ion/data/enron-spam/raw/spam/GP.tar.gz http://www.aueb.gr/users/ion/data/enron-spam/raw/spam/SH.tar.gz
    - for file in *.tar.gz; do tar -zxf $file; rm $file ; done
    - popd

script:
    - coverage run --source=kittengroomer_email setup.py test

notifications:
    email:
        on_success: change
        on_failure: change

after_success:
    - coveralls
    - codecov
